### ISSUE TITLE
Freezes at activationEvent: 'onView:dash.chatView'

### ISSUE THREAD

**Issue by alexxgarci** [Welltested-AI/fluttergpt#279]
### What version are you using?

v0.3.91

### What happened?

After installing the extension and setting the API key in extension settings, sidebar plugin freezes and UI keeps black.

### Steps to reproduce

```bash
1. Install extension.
2. Set API key from Gemini AI.
3. Open chat view clicking the plugin.
```

### Relevant log output

```Shell
2024-05-22 12:12:17.676 [info] ExtensionService#_doActivateExtension WelltestedAI.fluttergpt, startup: false, activationEvent: 'onView:dash.chatView'
2024-05-22 12:12:17.791 [error] Activating extension WelltestedAI.fluttergpt failed due to an error:
2024-05-22 12:12:17.791 [error] Error: spawn Unknown system error -86
	at ChildProcess.spawn (node:internal/child_process:414:11)
	at Object.spawn (node:child_process:799:9)
	at _DartCLIClient.connect (/Users/alexgarcia/.vscode/extensions/welltestedai.fluttergpt-0.3.91/out/extension.js:92857:31)
	at _SetupManager.init (/Users/alexgarcia/.vscode/extensions/welltestedai.fluttergpt-0.3.91/out/extension.js:93192:23)
	at activate (/Users/alexgarcia/.vscode/extensions/welltestedai.fluttergpt-0.3.91/out/extension.js:94704:22)
	at async h.n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:6281)
	at async h.m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:6244)
	at async h.l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:5701)
```

**Comment by samyakkkk** [comment]
@alexxgarci thanks for reporting this. Does the issue persist if you restart VSCode?

**Comment by samyakkkk** [comment]
@alexxgarci diving deeper into it - the issue usually [happens](https://github.com/puppeteer/puppeteer/issues/9142) when there is a mismatch in the system architecture and our engine binary we send. 

I assume you must me on Mac with ARM architecture CPU (m series). Is that correct?

**Comment by alexxgarci** [comment]
@samyakkkk The issue still persists if i restart the VSCode. And i'm running it on a Imac 21.5-inch, 2017 2,3 GHz Dual-Core Intel Core i5.

**Comment by samyakkkk** [comment]
@alexxgarci we've resolved the issue. our GitHub runners to compile for Mac got auto updated to arm64 and hence it stopped to work on intel Macs.

we've rolled it back. can you delete the commanddash binary in this path on your system: `/Users/{username}/Library/Application Support/Code/User/globalStorage`

and restart the extension? it should start working. plmk if it doesn't. thanks

**Comment by alexxgarci** [comment]
@samyakkkk Perfect. Now the extension works well, thanks for all!

**Comment by samyakkkk** [comment]
great! closing the issues. @alexxgarci do let us know if you've any other feedback!
